aemsites/piramal

- blocks/cards/cards.css
- blocks/cards/cards.js
Fix #5 
Test URLs:
- After: https://cards-block-variation-1--piramal--aemsites.hlx.page/
> Cards block - Variation 1 

- styles/styles.css
Fix #29 
Test URLs:
- After: https://29-homepage-add-required-section-padding--piramal--aemsites.hlx.page
> convert margin to padding for sections

- blocks/teaser/teaser.css
- blocks/teaser/teaser.js
Teaser block: 
Has :
- 2 image CTAs for desktop and 1 normal button CTA on mobile
- Background img
Fix #7 
Test URLs:
- After: https://7-homepage-teaser-block--piramal--aemsites.hlx.page
> teaser block

- component-definition.json
- component-filters.json
- component-models.json
Content modeling for home loan page, model, filters, and defintions. 
NOTE: you have to merge this PR first before you can publish the home loan page.
Fix #23
Author URL:
https://author-p133703-e1305981.adobeaemcloud.com/ui#/@piramal/aem/universal-editor/canvas/author-p133703-e1305981.adobeaemcloud.com/content/piramalfinance-eds2/home-loans.html?ref=issue-23
> #23 Home Loan Content Modeling

- blocks/columns/columns.css
Added 2 variations for the column block:
badges + content-center/content-left
Fix #8 
Test URLs:
- After: https://8-homepage-columns-block--piramal--aemsites.hlx.page
> 8 homepage columns block

- blocks/accordion/accordion.css
- blocks/accordion/accordion.js
Add accordion block for the FAQ section in home loans
Fix #41 
Test URLs:
- After: https://41-faq-accordion-block--piramal--aemsites.hlx.page/home-loans
> faq accordion

- styles/styles.css
Fix #49 
Test URLs:
- After: https://issue-49--piramal--aemsites.hlx.page/home-loans
> minor fix: color codes

- blocks/columns/columns.css
- blocks/image-list/image-list.css
- styles/styles.css
Fix #38 
Test URLs:
- After: https://heading-and-font-sizes--piramal--aemsites.hlx.page
> review paddings and font sizes

- blocks/metro-cities/metro-cities.css
- styles/styles.css
Style the metro cities section on the home loans page
Fix #40 
Test URLs:
- After: https://home-loan-metro-cities--piramal--aemsites.hlx.page/home-loans
> Home loan metro cities

- component-definition.json
- component-filters.json
- component-models.json
Fix #57 
Test URLs:
- After: https://issue-57--piramal--aemsites.hlx.page/home-loans
> chore: update key-features block properties

- blocks/key-features/key-features.css
- blocks/key-features/key-features.js
Fix #71 
Test URLs:
- After: https://issue-71--piramal--aemsites.hlx.page/home-loans
> feat: placeholders handling in key-features block

- blocks/key-features/key-features.css
- blocks/key-features/key-features.js
Fix #73 
Test URLs:
- After: https://issue-73--piramal--aemsites.hlx.page/home-loans
> key features section styling

- .eslintrc.js
- component-models.json
- helix-query.yaml
- paths.json
Fix #68 
Test URLs:
- After: https://issue-68--piramal--aemsites.hlx.page
> feat: indexing and metadata setup

- blocks/table/table.css
Style the generic table block
Fix #53 
Test URLs:
- After: https://issue-53-generic-table--piramal--aemsites.hlx.page/home-loans
> Issue 53 generic table

- blocks/key-features/key-features.css
- blocks/key-features/key-features.js
Fix UE view for key-features block
Test URLs:
- After: https://fix-key-features-block-2--piramal--aemsites.hlx.page/home-loans
> Fix key features block UE view

- component-models.json
Fix #<gh-issue-id>
Test URLs:
- After: https://issue-76--piramal--aemsites.hlx.page/home-loans
Points covered:
- The title and desc are now combined in one richtext.
- the key features details are now added as containers
> chore: update modeling for loan product block

- component-definition.json
- component-filters.json
- component-models.json
Fix #91 
Test URLs:
- After: https://kyc-documents-table--piramal--aemsites.hlx.page/home-loans
> Kyc documents table

- component-definition.json
- component-filters.json
- component-models.json
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--piramal--aemsites.hlx.page/home-loans/
- After: https://kyc-documents-table--piramal--aemsites.hlx.page/home-loans
this removes the conflict with `required-documents` block
> chore: update id name for kyc-documents table

- blocks/required-documents/required-documents.css
- blocks/table/table.css
- blocks/table/table.js
Kyc documents table
Fix #92 
Test URLs:
- After: https://issue-97-table--piramal--aemsites.hlx.page/home-loans
> required documents table

- blocks/columns/columns.js
- blocks/footer/footer.css
- blocks/modal/modal.css
- package.json
- styles/styles.css
Fix #3 
Test URLs:
- After: https://issue-3--piramal--aemsites.hlx.page
> style done for footer component

- blocks/hero-carousel/hero-carousel.js
- scripts/editor-support.js
- styles/styles.css
- stops carousel rotation when in edit mode
- starts rotation when in preview
- selecting slide moves it into view
- editing reloads the edited slide
Fix none
Test URLs:
- Before:
https://author-p133703-e1305981.adobeaemcloud.com/ui#/@piramal/aem/universal-editor/canvas/author-p133703-e1305981.adobeaemcloud.com/content/piramalfinance-eds2/index.html
- After: 
https://author-p133703-e1305981.adobeaemcloud.com/ui#/@piramal/aem/universal-editor/canvas/author-p133703-e1305981.adobeaemcloud.com/content/piramalfinance-eds2/index.html?ref=edit-hero
> Make hero-carousel editable in UE

- blocks/testimonies/testimonies.js
- scripts/editor-support.js
Add editor support to the testimonies block
https://author-p133703-e1305981.adobeaemcloud.com/ui#/@piramal/aem/universal-editor/canvas/author-p133703-e1305981.adobeaemcloud.com/content/piramalfinance-eds2/index.html?ref=testimonies-editor-support
Test URLs:
- After: https://testimonies-editor-support--piramal--aemsites.hlx.page
> editor support test

- blocks/footer/footer.css
Fix aspect ratio for play store / app store icons in the footer
Test URLs:
- After: https://footer-icons-fix--piramal--aemsites.hlx.page
> Footer icons fix

- blocks/header/header.js
- scripts/editor-support.js
Code fix for header to match UE
Fix #118 
Test URLs:
- After: https://header-style-fix-2--piramal--aemsites.hlx.page
> Header style fix 2

- blocks/header/header.css
- blocks/header/header.js
Add logo element on the mobile view navbar
Test URLs:
- After: https://add-navbar-img-mobile--piramal--aemsites.hlx.page
> header add img to mobile nav
